routes/web.php
<?php

use App\Http\Controllers\Backend\CategoryController as BackendCategoryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductController as BackendProductController;
use App\Http\Controllers\Backend\TransaksiController as BackendTransaksiController;
use App\Http\Controllers\Backend\BannerController as BackendBannerController;
use App\Http\Controllers\Backend\ReviewController as BackendReviewController;
use App\Http\Controllers\Frontend\ProductController;
use App\Http\Controllers\Frontend\AccountController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CategoryController;
use App\Http\Controllers\Frontend\HistoryController;
use App\Http\Controllers\Frontend\HomeController;


Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::resource('kategori', CategoryController::class)->only('show');
Route::get('produk/cari', [ProductController::class, 'search'])->name('produk.cari');
Route::resource('produk', ProductController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function() {
    Route::post('keranjang/{cart}', [CartController::class, 'cart'])->name('keranjang.store');
Route::get('keranjang', [CartController::class, 'index'])->name('keranjang.index');
Route::put('keranjang/{cart}/update', [CartController::class, 'update'])->name('keranjang.update');
Route::delete('keranjang/{cart}/delete', [CartController::class, 'delete'])->name('keranjang.delete');
Route::get('keranjang/checkout', [CartController::class, 'checkout'])->name('keranjang.checkout');
Route::put('payment/{payment}', [CartController::class, 'payment'])->name('keranjang.payment');
Route::get('payment/success', function() {
    return view('frontend.pages.keranjang.payment-success');
})->name('payment.success');

Route::post('review', [HistoryController::class, 'review'])->name('review.store');
Route::resource('riwayat-pesanan', HistoryController::class)->only(['index', 'update']);

Route::resource('akun', AccountController::class)->only(['index', 'update']);
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class)->except('show');
    Route::get('user/data', [UserController::class, 'data'])->name('user.data');

    Route::resource('kategori', BackendCategoryController::class)->except('show');
    Route::get('kategori/data', [BackendCategoryController::class, 'data'])->name('kategori.data');

    Route::resource('produk', BackendProductController::class)->except('show');
    Route::get('produk/data', [BackendProductController::class, 'data'])->name('produk.data');
    Route::put('produk/foto/hapus/{id}', [BackendProductController::class, 'imgDestroy']);

    Route::resource('transaksi', BackendTransaksiController::class)->only('index');
    Route::get('transaksi/data', [BackendTransaksiController::class, 'data'])->name('transaksi.data');
    Route::put('transaksi/updateOrder/{id}', [BackendTransaksiController::class, 'updateOrder'])->name('transaksi.updateOrder');
    Route::put('transaksi/completeOrder/{id}', [BackendTransaksiController::class, 'completeOrder'])->name('transaksi.completeOrder');
    Route::put('transaksi/cancelOrder/{id}', [BackendTransaksiController::class, 'cancelOrder'])->name('transaksi.cancelOrder');

    Route::resource('banner', BackendBannerController::class)->except('show');
    Route::get('banner/data', [BackendBannerController::class, 'data'])->name('banner.data');

    Route::resource('ulasan', BackendReviewController::class)->except('show');
    Route::get('ulasan/data', [BackendReviewController::class, 'data'])->name('ulasan.data');
});

resources/views/backend/pages/produk/create.blade.php
@extends('layouts.backend')
@section('title', 'Tambah Produk')

@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="javascript: void(0);">Produk</a>
</li>
<li class="breadcrumb-item active">Tambah Produk</li>
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <form action="{{ route('admin.produk.store') }}" method="post">
            @csrf

            <div class="row">
                <div class="col-12 mb-3">
                    <label for="name" class="form-label">Nama Produk<sup class="text-danger">*</sup></label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror"
                        value="{{ old('name') }}" required>

                    @error('name')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-12 mb-3">
                    <label for="category">Kategori<sup class="text-danger">*</sup></label>
                    <select class="form-select @error('category') is-invalid @enderror" name="category" required
                        data-choices>
                        <option disabled selected>--- Pilih Kategori ---</option>
                        @foreach ($categories as $item)
                        <option value="{{ $item->id }}" @selected(old('category')==$item->id)>{{ $item->name }}
                        </option>
                        @endforeach
                    </select>

                    @error('category')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-5 mb-3">
                    <label for="price" class="form-label">Harga<sup class="text-danger">*</sup></label>
                    <input type="number" name="price" class="form-control @error('price') is-invalid @enderror"
                        value="{{ old('price') }}" required>

                    @error('price')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-3 mb-3">
                    <label for="stock" class="form-label">Stok<sup class="text-danger">*</sup></label>
                    <input type="stock" name="stock" class="form-control @error('stock') is-invalid @enderror"
                        value="{{ old('stock') }}" required>

                    @error('stock')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-4 mb-3">
                    <label for="weight" class="form-label">Berat (gram)<sup class="text-danger">*</sup></label>
                    <input type="weight" name="weight" class="form-control @error('weight') is-invalid @enderror"
                        value="{{ old('weight') }}" required>

                    @error('weight')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-12 mb-3">
                    <label for="description" class="form-label">Deskripsi Produk</label>
                    <textarea class="form-control @error('description') is-invalid @enderror" name="description"
                        id="description" cols="30" rows="10" required>{{ old('description') }}</textarea>

                    @error('description')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-12 mb-3">
                    <label for="foto">Foto Produk<sup class="text-danger">*</sup></label>

                    <input type="file" class="filepond filepond-input-multiple" multiple id="foto" name="foto[]"
                        data-allow-reorder="true" data-max-file-size="1MB" accept="image/*">
                    <small>Maksimum ukuran file adalah 1MB</small>
                </div>
            </div>
            <div class="grid g-3 float-end">
                <a href="{{ route('admin.produk.index') }}" class="btn btn-light">Kembali</a>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
    </div>

    </form>
</div>
</div>

@endsection

@push('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"
    type="text/css" />
<link rel="stylesheet" href="{{ URL::asset('assets/libs/filepond/filepond.min.css') }}" type="text/css" />
<link rel="stylesheet"
    href="{{ URL::asset('assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css" />
<link href="{{ URL::asset('assets/libs/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css" />
@endpush

@push('scripts')
<script src="{{ URL::asset('assets/libs/filepond/filepond.min.js') }}"></script>
<script src="{{ URL::asset('assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.js') }}">
</script>
<script
    src="{{ URL::asset('assets/libs/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min.js') }}">
</script>
<script
    src="{{ URL::asset('assets/libs/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min.js') }}">
</script>
<script src="{{ URL::asset('assets/libs/filepond-plugin-file-encode/filepond-plugin-file-encode.min.js') }}"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>

<script>
    // FilePond
FilePond.registerPlugin(
    // encodes the file as base64 data
    FilePondPluginFileEncode,
    // validates the size of the file
    FilePondPluginFileValidateSize,
    // corrects mobile image orientation
    FilePondPluginImageExifOrientation,
    // previews dropped images
    FilePondPluginImagePreview,
    FilePondPluginFileValidateType
);

const inputMultipleElements = document.querySelectorAll('#foto');

if(inputMultipleElements){
    // loop over input elements
    Array.from(inputMultipleElements).forEach(function (inputElement) {
        // create a FilePond instance at the input element location
        FilePond.create(inputElement), {
            acceptedFileTypes: ['image/*'],
        };
    })
}
</script>

<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js"></script>

<!-- Delete Image -->
<script src="{{ URL::asset('/assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>
@endpush

resources/views/backend/pages/produk/edit.blade.php
@extends('layouts.backend')
@section('title', 'Edit Produk')

@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="javascript: void(0);">Produk</a>
</li>
<li class="breadcrumb-item active">Edit Produk</li>
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <form action="{{ route('admin.produk.update', $product->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-12 mb-3">
                    <label for="name" class="form-label">Nama Produk<sup class="text-danger">*</sup></label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror"
                        value="{{ old('name') ?? $product->name }}" required>

                    @error('name')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-12 mb-3">
                    <label for="category">Kategori<sup class="text-danger">*</sup></label>
                    <select class="form-select @error('category') is-invalid @enderror" name="category" required>
                        <option disabled selected>--- Pilih Kategori ---</option>
                        @foreach ($categories as $item)
                        <option value="{{ $item->id }}" @selected(old('role')==$item->id || $product->category_id ==
                            $item->id)>{{ $item->name }}</option>
                        @endforeach
                    </select>

                    @error('category')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-5 mb-3">
                    <label for="price" class="form-label">Harga<sup class="text-danger">*</sup></label>
                    <input type="text" name="price" class="form-control @error('price') is-invalid @enderror"
                        value="{{ old('price') ?? $product->price }}" required>

                    @error('price')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-3 mb-3">
                    <label for="stock" class="form-label">Stok<sup class="text-danger">*</sup></label>
                    <input type="text" name="stock" class="form-control @error('stock') is-invalid @enderror"
                        value="{{ old('stock') ?? $product->stock }}" required>

                    @error('stock')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-4 mb-3">
                    <label for="weight" class="form-label">Berat (gram)<sup class="text-danger">*</sup></label>
                    <input type="text" name="weight" class="form-control @error('weight') is-invalid @enderror"
                        value="{{ old('weight') ?? $product->weight }}" required>

                    @error('weight')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="description" class="form-label">Deskripsi Produk<sup class="text-danger">*</sup></label>
                    <textarea class="form-control @error('description') is-invalid @enderror" name="description"
                        id="description" cols="30" rows="10"
                        required>{{ old('description') ?? $product->description }}</textarea>

                    @error('description')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="col-12 mb-3">
                    <label for="foto">Foto Produk</label>
                    @if (!$product->galleries->isEmpty())
                    <div class="my-2 alert alert-info" id="info-foto">
                        <span>Foto produk yang sudah di input: </span>
                        <div class="d-flex flex-wrap gap-2 my-2">
                            @foreach ($product->galleries as $foto)
                            <a href="{{ url('storage/product', $foto->image) }}" data-fancybox="gallery2"
                                data-caption="{{ $foto->name }}">
                                <div class="position-relative">
                                    <img src="{{ url('storage/product', $foto->image) }}" alt="{{ $foto->name }}"
                                        width="80" class="img-fluid img-thumbnail">

                                    <div class="position-absolute" style="top: -10px; right: -5px;"
                                        id="foto-{{ $foto->id }}"
                                        onclick="event.preventDefault();imgDestroy({{ $foto->id }});">
                                        <i class="ri-close-circle-fill text-danger fs-4"></i>
                                    </div>
                                </div>
                            </a>
                            @endforeach
                        </div>
                        <p class="m-0">Tekan tombol silang untuk menghapus foto.</p>
                        <p class="m-0">Upload foto jika ingin menambahkan foto produk.</p>
                    </div>
                    @endif
                    <input type="file" class="filepond filepond-input-multiple" multiple id="foto" name="foto[]"
                        data-allow-reorder="true" data-max-file-size="2MB" accept="image/*">
                    <small>Maksimum ukuran file adalah 2MB</small>
                </div>
            </div>
            <div class="grid g-3 float-end">
                <a href="{{ route('admin.produk.index') }}" class="btn btn-light">Kembali</a>
                <button type="submit" class="btn btn-primary">Ubah</button>
            </div>
    </div>

    </form>
</div>
</div>

@endsection

@push('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"
    type="text/css" />
<link rel="stylesheet" href="{{ URL::asset('assets/libs/filepond/filepond.min.css') }}" type="text/css" />
<link rel="stylesheet"
    href="{{ URL::asset('assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css" />
<link href="{{ URL::asset('assets/libs/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css" />
@endpush

@push('scripts')
<!--jquery cdn-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{{ URL::asset('assets/libs/filepond/filepond.min.js') }}"></script>
<script src="{{ URL::asset('assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.js') }}">
</script>
<script
    src="{{ URL::asset('assets/libs/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min.js') }}">
</script>
<script
    src="{{ URL::asset('assets/libs/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min.js') }}">
</script>
<script src="{{ URL::asset('assets/libs/filepond-plugin-file-encode/filepond-plugin-file-encode.min.js') }}"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>

<script>
    // FilePond
FilePond.registerPlugin(
    // encodes the file as base64 data
    FilePondPluginFileEncode,
    // validates the size of the file
    FilePondPluginFileValidateSize,
    // corrects mobile image orientation
    FilePondPluginImageExifOrientation,
    // previews dropped images
    FilePondPluginImagePreview,
    FilePondPluginFileValidateType
);

const inputMultipleElements = document.querySelectorAll('#foto');

if(inputMultipleElements){
// loop over input elements
Array.from(inputMultipleElements).forEach(function (inputElement) {
    // create a FilePond instance at the input element location
    FilePond.create(inputElement), {
        acceptedFileTypes: ['image/*'],
    };
})
}

</script>

<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js"></script>

<!-- Delete Image -->
<script src="{{ URL::asset('/assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>

<script>
    let jmlFoto = {{ $product->galleries->count() }}

    function imgDestroy(id) {
        let el = event.target.parentElement.parentElement.parentElement;

        Swal.fire({
            html: '<div class="mt-3">' +
                '<lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop" colors="primary:#f7b84b,secondary:#f06548" style="width:100px;height:100px"></lord-icon>' +
                '<div class="mt-4 pt-2 fs-15 mx-5">' +
                '<h4>Anda Yakin ?</h4>' +
                '<p class="text-muted mx-4 mb-0">Anda yakin ingin menghapus foto ini ?</p>' +
                '</div>' +
                '</div>',
            showCancelButton: true,
            reverseButtons: true,
            confirmButtonClass: 'btn btn-primary w-xs mb-1',
            confirmButtonText: 'Ya, Hapus!',
            cancelButtonClass: 'btn btn-danger w-xs mb-1 me-2',
            cancelButtonText: 'Batal',
            buttonsStyling: false,
            showCloseButton: true
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '/admin/produk/foto/hapus/' + id,
                    method: 'put',
                    context: el,
                    data: {
                        _token: '{{ csrf_token() }}',
                    },
                    success: function(data) {
                        Toastify({
                            text: "Foto berhasil dihapus",
                            duration: 5000,
                            close: true,
                            gravity: "top", // `top` or `bottom`
                            position: "right", // `left`, `center` or `right`
                            stopOnFocus: true, // Prevents dismissing of toast on hover
                            className: 'bg-primary',
                            style: {
                                background: "linear-gradient(to right, rgb(10, 179, 156), rgb(64, 81, 137))"
                            },
                            onClick: function() {} // Callback after click
                        }).showToast();

                        jmlFoto--;
                        el.remove();

                        jmlFoto == 0 ? hideInfoFoto() : '';
                    }
                })
            }
        })
    }

    const hideInfoFoto = () => {
        return $('#info-foto').addClass('d-none');
    }
</script>
@endpush

resources/views/backend/pages/produk/index.blade.php
@extends('layouts.backend')
@section('title', 'Data Produk')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="javascript: void(0);">Produk</a>
    </li>
    <li class="breadcrumb-item active">List Produk</li>
@endsection

@section('content')
    <div class="card">
        <div class="card-header d-flex justify-content-end mb-3">
            <a href="{{ route('admin.produk.create') }}" class="btn btn-primary">Tambah Data</a>
        </div>
        <div class="card-body">
            <table id="datatable" class="table data nowrap dt-responsive align-middle table-hover table-bordered"
                style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nama Produk</th>
                        <th>Kategori</th>
                        <th>Harga</th>
                        <th>Stok</th>
                        <th>Berat (g)</th>
                        <th style="width:5%;">Aksi</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>

    @foreach ($products as $data)
        <!-- Foto Produk -->
        <div id="modalFoto-{{ $data->id }}" class="modal fade" tabindex="-1" aria-labelledby="myModalLabel"
            aria-hidden="true" style="display: none;">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="myModalLabel">{{ $data->name }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="d-flex flex-wrap gap-3">
                            @foreach ($data->galleries as $foto)
                                <img src="{{ url('storage/product', $foto->image) }}" width="100"
                                    alt="{{ $foto->name }}" class="img-thumbnail img-fluid">
                            @endforeach
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Tutup</button>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@endsection

@push('styles')
    <!--datatable css-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <!--datatable responsive css-->
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
    <!-- Sweet Alert css-->
    <link href="{{ asset('assets/libs/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css" />
@endpush

@push('scripts')
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--datatable js-->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>

    <script>
        $(document).ready(function() {
            let table = $('#datatable').DataTable({
                processing: true,
                serverSide: true,
                order: [
                    [1, "asc"]
                ],
                ajax: {
                    url: '{{ route('admin.produk.data') }}',
                },
                columns: [{
                        data: null,
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'category',
                        name: 'category.name'
                    },
                    {
                        data: 'price',
                        name: 'price'
                    },
                    {
                        data: 'stock',
                        name: 'stock'
                    },
                    {
                        data: 'weight',
                        name: 'weight'
                    },
                    {
                        data: 'aksi',
                        name: 'aksi',
                        orderable: false,
                        searchable: false,
                    },
                ]
            });
        });
    </script>
    <!-- Sweet Alerts js -->
    <script src="{{ asset('assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>

    {{-- Delete Data Sweet Alert --}}
    <script>
        const confirmDelete = id => {
            Swal.fire({
                html: '<div class="mt-3">' +
                    '<lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop" colors="primary:#f7b84b,secondary:#f06548" style="width:100px;height:100px"></lord-icon>' +
                    '<div class="mt-4 pt-2 fs-15 mx-5">' +
                    '<h4>Anda Yakin ?</h4>' +
                    '<p class="text-muted mx-4 mb-0">Anda yakin ingin menghapus data ini ?</p>' +
                    '</div>' +
                    '</div>',
                showCancelButton: true,
                reverseButtons: true,
                confirmButtonClass: 'btn btn-primary w-xs mb-1',
                confirmButtonText: 'Ya, Hapus!',
                cancelButtonClass: 'btn btn-danger w-xs mb-1 me-2',
                cancelButtonText: 'Batal',
                buttonsStyling: false,
                showCloseButton: true
            }).then((result) => {
                if (result.isConfirmed) {
                    $(`#delete-${id}`).submit();
                    Swal.fire(
                        'Dihapus!', 'Data berhasil dihapus.', 'success'
                    )
                }
            })
        }
    </script>
@endpush