routes/web.php
<?php

use App\Http\Controllers\Backend\CategoryController as BackendCategoryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductController as BackendProductController;
use App\Http\Controllers\Backend\TransaksiController as BackendTransaksiController;
use App\Http\Controllers\Backend\BannerController as BackendBannerController;
use App\Http\Controllers\Backend\ReviewController as BackendReviewController;
use App\Http\Controllers\Frontend\ProductController;
use App\Http\Controllers\Frontend\AccountController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CategoryController;
use App\Http\Controllers\Frontend\HistoryController;
use App\Http\Controllers\Frontend\HomeController;


Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::resource('kategori', CategoryController::class)->only('show');
Route::get('produk/cari', [ProductController::class, 'search'])->name('produk.cari');
Route::resource('produk', ProductController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function() {
    Route::post('keranjang/{cart}', [CartController::class, 'cart'])->name('keranjang.store');
Route::get('keranjang', [CartController::class, 'index'])->name('keranjang.index');
Route::put('keranjang/{cart}/update', [CartController::class, 'update'])->name('keranjang.update');
Route::delete('keranjang/{cart}/delete', [CartController::class, 'delete'])->name('keranjang.delete');
Route::get('keranjang/checkout', [CartController::class, 'checkout'])->name('keranjang.checkout');
Route::put('payment/{payment}', [CartController::class, 'payment'])->name('keranjang.payment');
Route::get('payment/success', function() {
    return view('frontend.pages.keranjang.payment-success');
})->name('payment.success');

Route::post('review', [HistoryController::class, 'review'])->name('review.store');
Route::resource('riwayat-pesanan', HistoryController::class)->only(['index', 'update']);

Route::resource('akun', AccountController::class)->only(['index', 'update']);
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class)->except('show');
    Route::get('user/data', [UserController::class, 'data'])->name('user.data');

    Route::resource('kategori', BackendCategoryController::class)->except('show');
    Route::get('kategori/data', [BackendCategoryController::class, 'data'])->name('kategori.data');

    Route::resource('produk', BackendProductController::class)->except('show');
    Route::get('produk/data', [BackendProductController::class, 'data'])->name('produk.data');
    Route::put('produk/foto/hapus/{id}', [BackendProductController::class, 'imgDestroy']);

    Route::resource('transaksi', BackendTransaksiController::class)->only('index');
    Route::get('transaksi/data', [BackendTransaksiController::class, 'data'])->name('transaksi.data');
    Route::put('transaksi/updateOrder/{id}', [BackendTransaksiController::class, 'updateOrder'])->name('transaksi.updateOrder');
    Route::put('transaksi/completeOrder/{id}', [BackendTransaksiController::class, 'completeOrder'])->name('transaksi.completeOrder');
    Route::put('transaksi/cancelOrder/{id}', [BackendTransaksiController::class, 'cancelOrder'])->name('transaksi.cancelOrder');

    Route::resource('banner', BackendBannerController::class)->except('show');
    Route::get('banner/data', [BackendBannerController::class, 'data'])->name('banner.data');

    Route::resource('ulasan', BackendReviewController::class)->except('show');
    Route::get('ulasan/data', [BackendReviewController::class, 'data'])->name('ulasan.data');
});

resources/views/backend/pages/kategori/create.blade.php
@extends('layouts.backend')
@section('title', 'Kategori')
@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="javascript: void(0);">Kategori</a>
</li>
<li class="breadcrumb-item active">Tambah Kategori</li>
@endsection
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form action="{{ route('admin.kategori.store') }}" method="post">
                    @csrf

                    <div class="mb-3">
                        <label for="name" class="form-label">Nama Kategori<sup class="text-danger">*</sup></label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                            name="name" value="{{ old('name') }}" required>
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="icon" class="form-label">Icon<sup class="text-danger">*</sup></label>
                        <input type="file" class="filepond" id="icon" name="icon" data-max-file-size="2MB"
                            accept="image/*" required>
                        <small class="text-black-50">Maksimum ukuran file adalah 2MB</small>
                        @error('icon')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="d-flex justify-content-end mt-3 gap-2">
                        <a href="{{ route('admin.kategori.index') }}" class="btn btn-light">Kembali</a>
                        <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
<link rel="stylesheet" href="{{ URL::asset('assets/libs/filepond/filepond.min.css') }}" type="text/css" />
<link rel="stylesheet"
    href="{{ URL::asset('assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.css') }}">
@endpush

@push('scripts')
<script src="{{ URL::asset('assets/libs/filepond/filepond.min.js') }}"></script>
<script src="{{ URL::asset('assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.js') }}">
</script>
<script
    src="{{ URL::asset('assets/libs/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min.js') }}">
</script>
<script
    src="{{ URL::asset('assets/libs/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min.js') }}">
</script>
<script src="{{ URL::asset('assets/libs/filepond-plugin-file-encode/filepond-plugin-file-encode.min.js') }}"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>

<script>
    // FilePond
FilePond.registerPlugin(
    // encodes the file as base64 data
    FilePondPluginFileEncode,
    // validates the size of the file
    FilePondPluginFileValidateSize,
    // corrects mobile image orientation
    FilePondPluginImageExifOrientation,
    // previews dropped images
    FilePondPluginImagePreview,
    FilePondPluginFileValidateType
);

FilePond.create(document.querySelector('#icon'));
</script>
@endpush

resources/views/backend/pages/kategori/edit.blade.php
@extends('layouts.backend')
@section('title', 'Kategori')
@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="javascript: void(0);">Kategori</a>
</li>
<li class="breadcrumb-item active">Edit Kategori</li>
@endsection
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form action="{{ route('admin.kategori.update', $item->id) }}" method="post">
                    @csrf
                    @method('PUT')

                    <div class="mb-3">
                        <label for="name" class="form-label">Nama Kategori<sup class="text-danger">*</sup></label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                            name="name" value="{{ old('name') ?? $item->name }}" required>
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="icon" class="form-label">Icon</label>
                        <small class="d-block text-black-50">Catatan: Icon sudah tersedia, <a href="{{ url('storage/kategori', $item->icon) }}" data-fancybox="{{ $item->name }}" data-caption="{{ $item->name }}">Lihat disini</a>. Upload jika ingin mengganti icon</small>
                        <input type="file" class="filepond" id="icon" name="icon" data-max-file-size="2MB"
                            accept="image/*">
                        <small class="text-black-50">Maksimum ukuran file adalah 2MB</small>
                        @error('icon')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="d-flex justify-content-end gap-2 mt-3">
                        <a href="{{ route('admin.kategori.index') }}" class="btn btn-light">Kembali</a>
                        <button type="submit" class="btn btn-primary">Ubah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
<link rel="stylesheet" href="{{ URL::asset('assets/libs/filepond/filepond.min.css') }}" type="text/css" />
<link rel="stylesheet"
    href="{{ URL::asset('assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.css') }}">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css" />
@endpush

@push('scripts')
<script src="{{ URL::asset('assets/libs/filepond/filepond.min.js') }}"></script>
<script src="{{ URL::asset('assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.js') }}">
</script>
<script
    src="{{ URL::asset('assets/libs/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min.js') }}">
</script>
<script
    src="{{ URL::asset('assets/libs/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min.js') }}">
</script>
<script src="{{ URL::asset('assets/libs/filepond-plugin-file-encode/filepond-plugin-file-encode.min.js') }}"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>

<script>
    // FilePond
FilePond.registerPlugin(
    // encodes the file as base64 data
    FilePondPluginFileEncode,
    // validates the size of the file
    FilePondPluginFileValidateSize,
    // corrects mobile image orientation
    FilePondPluginImageExifOrientation,
    // previews dropped images
    FilePondPluginImagePreview,
    FilePondPluginFileValidateType
);

FilePond.create(document.querySelector('#icon'));
</script>
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js"></script>
@endpush

resources/views/backend/pages/kategori/index.blade.php
@extends('layouts.backend')
@section('title', 'Kategori')
@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="javascript: void(0);">Kategori</a>
</li>
<li class="breadcrumb-item active">List Kategori</li>
@endsection

@section('content')
<div class="card">
    <div class="card-header">
        <div class="d-grid justify-content-end">
            <a href="{{ route('admin.kategori.create') }}" class="btn btn-primary brn waves-effect waves-light">Tambah
                Kategori
            </a>
        </div>
    </div>

    <div class="card-body">
        <table id="datatable" class="table data nowrap dt-responsive align-middle table-hover table-bordered"
            style="width:100%">
            <thead>
                <tr>
                    <th class="text-center" style="width: 25px">#</th>
                    <th>Nama</th>
                    <th>Icon</th>
                    <th style="width:7%;">Aksi</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@endsection

@push('styles')
<!--datatable css-->
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
<!--datatable responsive css-->
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap.min.css" />
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
<!-- Sweet Alert css-->
<link href="{{ asset('assets/libs/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css" />
@endpush

@push('scripts')
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<!--datatable js-->
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>

<script>
    $(document).ready(function() {
            let table = $('#datatable').DataTable({
                processing: true,
                serverSide: true,
                order: [
                    [1, "asc"]
                ],
                ajax: {
                    url: '{{ route('admin.kategori.data') }}',
                },
                columns: [
                    {
                        data: null,
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'icon',
                        name: 'icon'
                    },
                    {
                        data: 'aksi',
                        name: 'aksi',
                        orderable: false,
                        searchable: false,
                    },
                ]
            });
        });
</script>
<!-- Sweet Alerts js -->
<script src="{{ asset('assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>

{{-- Delete Data Sweet Alert --}}
<script>
    const confirmDelete = id => {
            Swal.fire({
                html: '<div class="mt-3">' +
                    '<lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop" colors="primary:#f7b84b,secondary:#f06548" style="width:100px;height:100px"></lord-icon>' +
                    '<div class="mt-4 pt-2 fs-15 mx-5">' +
                    '<h4>Anda Yakin ?</h4>' +
                    '<p class="text-muted mx-4 mb-0">Anda yakin ingin menghapus data ini ?</p>' +
                    '</div>' +
                    '</div>',
                showCancelButton: true,
                reverseButtons: true,
                confirmButtonClass: 'btn btn-primary w-xs mb-1',
                confirmButtonText: 'Ya, Hapus!',
                cancelButtonClass: 'btn btn-danger w-xs mb-1 me-2',
                cancelButtonText: 'Batal',
                buttonsStyling: false,
                showCloseButton: true
            }).then((result) => {
                if (result.isConfirmed) {
                    $(`#delete-${id}`).submit();
                    Swal.fire(
                        'Dihapus!', 'Data berhasil dihapus.', 'success'
                    )
                }
            })
        }
</script>

<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js"></script>
@endpush