routes/web.php
<?php

use App\Http\Controllers\Backend\CategoryController as BackendCategoryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductController as BackendProductController;
use App\Http\Controllers\Backend\TransaksiController as BackendTransaksiController;
use App\Http\Controllers\Backend\BannerController as BackendBannerController;
use App\Http\Controllers\Backend\ReviewController as BackendReviewController;
use App\Http\Controllers\Frontend\ProductController;
use App\Http\Controllers\Frontend\AccountController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CategoryController;
use App\Http\Controllers\Frontend\HistoryController;
use App\Http\Controllers\Frontend\HomeController;


Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::resource('kategori', CategoryController::class)->only('show');
Route::get('produk/cari', [ProductController::class, 'search'])->name('produk.cari');
Route::resource('produk', ProductController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function() {
    Route::post('keranjang/{cart}', [CartController::class, 'cart'])->name('keranjang.store');
Route::get('keranjang', [CartController::class, 'index'])->name('keranjang.index');
Route::put('keranjang/{cart}/update', [CartController::class, 'update'])->name('keranjang.update');
Route::delete('keranjang/{cart}/delete', [CartController::class, 'delete'])->name('keranjang.delete');
Route::get('keranjang/checkout', [CartController::class, 'checkout'])->name('keranjang.checkout');
Route::put('payment/{payment}', [CartController::class, 'payment'])->name('keranjang.payment');
Route::get('payment/success', function() {
    return view('frontend.pages.keranjang.payment-success');
})->name('payment.success');

Route::post('review', [HistoryController::class, 'review'])->name('review.store');
Route::resource('riwayat-pesanan', HistoryController::class)->only(['index', 'update']);

Route::resource('akun', AccountController::class)->only(['index', 'update']);
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class)->except('show');
    Route::get('user/data', [UserController::class, 'data'])->name('user.data');

    Route::resource('kategori', BackendCategoryController::class)->except('show');
    Route::get('kategori/data', [BackendCategoryController::class, 'data'])->name('kategori.data');

    Route::resource('produk', BackendProductController::class)->except('show');
    Route::get('produk/data', [BackendProductController::class, 'data'])->name('produk.data');
    Route::put('produk/foto/hapus/{id}', [BackendProductController::class, 'imgDestroy']);

    Route::resource('transaksi', BackendTransaksiController::class)->only('index');
    Route::get('transaksi/data', [BackendTransaksiController::class, 'data'])->name('transaksi.data');
    Route::put('transaksi/updateOrder/{id}', [BackendTransaksiController::class, 'updateOrder'])->name('transaksi.updateOrder');
    Route::put('transaksi/completeOrder/{id}', [BackendTransaksiController::class, 'completeOrder'])->name('transaksi.completeOrder');
    Route::put('transaksi/cancelOrder/{id}', [BackendTransaksiController::class, 'cancelOrder'])->name('transaksi.cancelOrder');

    Route::resource('banner', BackendBannerController::class)->except('show');
    Route::get('banner/data', [BackendBannerController::class, 'data'])->name('banner.data');

    Route::resource('ulasan', BackendReviewController::class)->except('show');
    Route::get('ulasan/data', [BackendReviewController::class, 'data'])->name('ulasan.data');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'no_telp',
        'password',
        'address',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\User;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function index()
    {
        return view('backend.pages.user.index');
    }

    public function data()
    {
        $data = User::orderBy('name')->get();

        return DataTables::of($data)
            ->addColumn('roles', function ($data) {
                if ($data->getRoleNames()[0] === 'admin') {
                    $td = '<span class="badge badge-gradient-primary ">' . $data->getRoleNames()[0] . '</span>';
                } else {
                    $td = ' <span class="badge badge-gradient-danger ">' . $data->getRoleNames()[0] . '</span>';
                }
                return $td;
            })
            ->addColumn('aksi', function ($data) {
                $button = '<a href="' . route('admin.user.edit', $data->id) . '" class="btn btn-sm btn-soft-info me-1">Edit</a>';

                $button .= '<a href="#" class="btn btn-sm btn-soft-danger" onclick="confirmDelete(' . $data->id . ')">
            <form action="' . route('admin.user.destroy', $data->id) . '" method="POST"
                id="delete-' . $data->id . '"><input type="hidden" name="_token" value="' . csrf_token() . '" /><input type="hidden" name="_method" value="delete" /></form>Hapus</a>';

                return $button;
            })
            ->rawColumns(['roles', 'aksi'])
            ->make(true);
    }

    public function create()
    {
        $roles = Role::all()->pluck('name');
        return view('backend.pages.user.create', compact('roles'));
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required'],
            'username' => ['required', 'unique:users'],
            'email' => ['required', 'unique:users'],
            'password' => ['required', 'string', 'min:8'],
            'no_telp' => ['numeric', 'nullable'],
            'role' => ['required']
        ]);

        User::create([
            'name' => $data['name'],
            'username' => $data['username'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
            'no_telp' => $data['no_telp']
        ])->assignRole($data['role']);

        return view('backend.pages.user.index');
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all()->pluck('name');
        return view('backend.pages.user.edit', [
            'user' => $user,
            'roles' => $roles
        ]);
    }

    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $data = $request->validate([
            'name' => ['required'],
            'username' => ['required', 'unique:users,username,' . $user->id],
            'email' => ['required', 'unique:users,email,' . $user->id],
            'password' => ['sometimes', 'required', 'string', 'min:8'],
            'no_telp' => ['numeric', 'max_digits: 13'],
            'role' => ['required']
        ], [
            '*.required' => ':attribute harus diisi.',
            '*.string' => ':attribute harus berupa string.',
            '*.max' => 'panjang :attribute tidak boleh lebih dari :max karakter.',
            '*.unique' => ':attribute sudah digunakan.',
            '*.numeric' => ':attribute harus berupa angka.',
            '*.min' => ':attribute minimal :min karakter.',
            '*.max_digits' => ':attribute tidak boleh lebih dari :max digit.',
        ], [
            'name' => 'nama',
            'no_telp' => 'no. handphone',
        ]);

        $user->update([
            'name' => $data['name'],
            'username' => $data['username'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
            'no_telp' => $data['no_telp']
        ]);

        $user->syncRoles($data['role']);

        return view('backend.pages.user.index');
    }

    public function destroy($id)
    {
        $data = User::findOrFail($id);
        $data->delete();

        return view('backend.pages.user.index');
    }
}

resources/views/backend/pages/user/create.blade.php
@extends('layouts.backend')
@section('title', 'Tambah Pengguna')

@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="javascript: void(0);">Pengguna</a>
</li>
<li class="breadcrumb-item active">Tambah Pengguna</li>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.user.store') }}" method="post">
                @csrf
                <div class="mb-3">
                    <label for="name" class="form-label">Nama Lengkap</label>
                    <input type="text" name="name" id="name"
                        class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}" required>

                    @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control @error('username') is-invalid @enderror"
                        value="{{ old('username') }}" required>

                    @error('username')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" class="form-control @error('email') is-invalid @enderror"
                        value="{{ old('email') }}" required>

                    @error('email')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="no_telp" class="form-label">Nomor Telepon</label>
                    <input type="number" name="no_telp" class="form-control @error('no_telp') is-invalid @enderror"
                        value="{{ old('no_telp') }}" required>

                    @error('no_telp')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="role">Role</label>
                    <select class="form-select @error('role') is-invalid @enderror" name="role" required data-choices>
                        <option disabled selected>--- Pilih Role ---</option>
                        @foreach ($roles as $item)
                            <option value="{{ $item }}" @selected(old('role') == $item)>{{ $item }}
                            </option>
                        @endforeach
                    </select>

                    @error('role')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" id="password"
                        class="form-control @error('password') is-invalid @enderror" required>

                    @error('password')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="grid g-3 float-end">
                    <a href="{{ route('admin.user.index') }}" class="btn btn-light">Kembali</a>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>

@endsection
@push('scripts')
@endpush

resources/views/backend/pages/user/edit.blade.php
@extends('layouts.backend')
@section('title', 'Edit Pengguna')

@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="javascript: void(0);">Pengguna</a>
</li>
<li class="breadcrumb-item active">Edit Pengguna</li>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.user.update', $user->id) }}" method="post">
                @csrf
                @method('PUT')
                <div class="mb-3">
                    <label for="name" class="form-label">Nama Lengkap</label>
                    <input type="text" name="name" id="name"
                        class="form-control @error('name') is-invalid @enderror" value="{{ old('name') ?? $user->name }}"
                        required>

                    @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control @error('username') is-invalid @enderror"
                        value="{{ old('username') ?? $user->username }}" required>

                    @error('username')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" class="form-control @error('email') is-invalid @enderror"
                        value="{{ old('email') ?? $user->email }}" required>

                    @error('email')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="no_telp" class="form-label">Nomor Telepon</label>
                    <input type="number" name="no_telp" class="form-control @error('no_telp') is-invalid @enderror"
                        value="{{ old('no_telp') ?? $user->no_telp }}" required>

                    @error('no_telp')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="role">Role</label>
                    <select class="form-select @error('role') is-invalid @enderror" name="role" required>
                        <option disabled selected>--- Pilih Role ---</option>
                        @foreach ($roles as $item)
                            <option value="{{ $item }}" @selected(old('role') == $item || $user->getRoleNames()[0] == $item)>{{ $item }}</option>
                        @endforeach
                    </select>

                    @error('role')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" id="password"
                        class="form-control @error('password') is-invalid @enderror" required>

                    @error('password')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="grid g-3 float-end">
                    <a href="{{ route('admin.user.index') }}" class="btn btn-light">Kembali</a>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
@endsection
@push('scripts')
@endpush

resources/views/backend/pages/user/index.blade.php
@extends('layouts.backend')
@section('title', 'Data Pengguna')

@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="javascript: void(0);">Pengguna</a>
</li>
<li class="breadcrumb-item active">List Pengguna</li>
@endsection

@section('content')
    <div class="card">
        <div class="card-header d-flex justify-content-end mb-3">
            <a href="{{ route('admin.user.create') }}" class="btn btn-primary">Tambah Data</a>
        </div>
        <div class="card-body">
            <table id="alternative-pagination"
                class="table data nowrap dt-responsive align-middle table-hover table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nama</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th style="width:5%;">Roles</th>
                        <th>Nomor Telpon</th>
                        <th style="width:7%;">Aksi</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection

@push('styles')
    <!--datatable css-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <!--datatable responsive css-->
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
    <!-- Sweet Alert css-->
    <link href="{{ asset('assets/libs/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css" />
@endpush

@push('scripts')
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--datatable js-->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>

    <script>
        $(document).ready(function() {
            let table = $('#alternative-pagination').DataTable({
                processing: true,
                serverSide: true,
                order: [
                    [1, "asc"]
                ],
                ajax: {
                    url: '{{ route('admin.user.data') }}',
                },
                columns: [{
                        data: null,
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'username',
                        name: 'username'
                    },
                    {
                        data: 'email',
                        name: 'email'
                    },
                    {
                        data: 'roles',
                        name: 'roles'
                    },
                    {
                        data: 'no_telp',
                        name: 'no_telp'
                    },
                    {
                        data: 'aksi',
                        name: 'aksi',
                        orderable: false,
                        searchable: false,
                    },
                ]
            });
        });
    </script>
    <!-- Sweet Alerts js -->
    <script src="{{ asset('assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>

    {{-- Delete Data Sweet Alert --}}
    <script>
        const confirmDelete = id => {
            Swal.fire({
                html: '<div class="mt-3">' +
                    '<lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop" colors="primary:#f7b84b,secondary:#f06548" style="width:100px;height:100px"></lord-icon>' +
                    '<div class="mt-4 pt-2 fs-15 mx-5">' +
                    '<h4>Anda Yakin ?</h4>' +
                    '<p class="text-muted mx-4 mb-0">Anda yakin ingin menghapus data ini ?</p>' +
                    '</div>' +
                    '</div>',
                showCancelButton: true,
                reverseButtons: true,
                confirmButtonClass: 'btn btn-primary w-xs mb-1',
                confirmButtonText: 'Ya, Hapus!',
                cancelButtonClass: 'btn btn-danger w-xs mb-1 me-2',
                cancelButtonText: 'Batal',
                buttonsStyling: false,
                showCloseButton: true
            }).then((result) => {
                if (result.isConfirmed) {
                    $(`#delete-${id}`).submit();
                    Swal.fire(
                        'Dihapus!', 'Data berhasil dihapus.', 'success'
                    )
                }
            })
        }
    </script>
@endpush