routes/web.php
<?php

use App\Http\Controllers\Backend\CategoryController as BackendCategoryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductController as BackendProductController;
use App\Http\Controllers\Backend\TransaksiController as BackendTransaksiController;
use App\Http\Controllers\Backend\BannerController as BackendBannerController;
use App\Http\Controllers\Backend\ReviewController as BackendReviewController;
use App\Http\Controllers\Frontend\ProductController;
use App\Http\Controllers\Frontend\AccountController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CategoryController;
use App\Http\Controllers\Frontend\HistoryController;
use App\Http\Controllers\Frontend\HomeController;


Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::resource('kategori', CategoryController::class)->only('show');
Route::get('produk/cari', [ProductController::class, 'search'])->name('produk.cari');
Route::resource('produk', ProductController::class)->only(['index', 'show']);

Route::middleware('auth')->group(function() {
    Route::post('keranjang/{cart}', [CartController::class, 'cart'])->name('keranjang.store');
Route::get('keranjang', [CartController::class, 'index'])->name('keranjang.index');
Route::put('keranjang/{cart}/update', [CartController::class, 'update'])->name('keranjang.update');
Route::delete('keranjang/{cart}/delete', [CartController::class, 'delete'])->name('keranjang.delete');
Route::get('keranjang/checkout', [CartController::class, 'checkout'])->name('keranjang.checkout');
Route::put('payment/{payment}', [CartController::class, 'payment'])->name('keranjang.payment');
Route::get('payment/success', function() {
    return view('frontend.pages.keranjang.payment-success');
})->name('payment.success');

Route::post('review', [HistoryController::class, 'review'])->name('review.store');
Route::resource('riwayat-pesanan', HistoryController::class)->only(['index', 'update']);

Route::resource('akun', AccountController::class)->only(['index', 'update']);
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class)->except('show');
    Route::get('user/data', [UserController::class, 'data'])->name('user.data');

    Route::resource('kategori', BackendCategoryController::class)->except('show');
    Route::get('kategori/data', [BackendCategoryController::class, 'data'])->name('kategori.data');

    Route::resource('produk', BackendProductController::class)->except('show');
    Route::get('produk/data', [BackendProductController::class, 'data'])->name('produk.data');
    Route::put('produk/foto/hapus/{id}', [BackendProductController::class, 'imgDestroy']);

    Route::resource('transaksi', BackendTransaksiController::class)->only('index');
    Route::get('transaksi/data', [BackendTransaksiController::class, 'data'])->name('transaksi.data');
    Route::put('transaksi/updateOrder/{id}', [BackendTransaksiController::class, 'updateOrder'])->name('transaksi.updateOrder');
    Route::put('transaksi/completeOrder/{id}', [BackendTransaksiController::class, 'completeOrder'])->name('transaksi.completeOrder');
    Route::put('transaksi/cancelOrder/{id}', [BackendTransaksiController::class, 'cancelOrder'])->name('transaksi.cancelOrder');

    Route::resource('banner', BackendBannerController::class)->except('show');
    Route::get('banner/data', [BackendBannerController::class, 'data'])->name('banner.data');

    Route::resource('ulasan', BackendReviewController::class)->except('show');
    Route::get('ulasan/data', [BackendReviewController::class, 'data'])->name('ulasan.data');
});

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Banner;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        $banners = Banner::latest()->get();
        $categories = Category::orderBy('name')->get();
        $products = Product::latest()->limit(16)->get();

        return view('frontend.pages.home.index', [
            'banners' => $banners,
            'categories' => $categories,
            'products' => $products
        ]);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function starter()
    {
        return view('layouts.backend');
    }

    public function index()
    {
        return view('home');
    }
}

resources/views/frontend/pages/home/index.blade.php
@extends('layouts.app')

@section('title', 'Pildun Store')

@section('content')
<!-- Banner -->
@if (!$banners->isEmpty())
<div id="banner" class="carousel slide rounded overflow-hidden" data-bs-ride="true">
    <div class="carousel-indicators">
        @foreach ($banners as $item)
        <button type="button" data-bs-target="#banner" data-bs-slide-to="0" @if($loop->first)
            class="active" aria-current="true" @endif aria-label="Slide {{ $loop->index + 1 }}"></button>
        @endforeach
    </div>
    <div class="carousel-inner">
        @foreach ($banners as $item)
        <div data-bs-interval="2000" class="carousel-item {{ $loop->first ? 'active' : '' }}">
            <img src="{{ url('storage/banner', $item->image) }}" class="d-block w-100">
        </div>
        @endforeach
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#banner" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#banner" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
@endif

<!-- Kategori -->
<section class="card border-0 py-3 shadow-sm my-4">
    <div class="card-body">
        <div class="row g-3 px-lg-5 justify-content-arround">
            @forelse ($categories as $item)
            <div class="col-4 col-lg-2 text-center">
                <a href="{{ route('kategori.show', $item->slug) }}" class="text-decoration-none text-dark">
                    <div class="card rounded mb-1">
                        <div class="card-body text-center">
                            <img src="{{ url('storage/kategori', $item->icon) }}" alt="{{ $item->name }}"
                                class="img-fluid" width="50" height="50">
                        </div>
                    </div>
                    <span>{{ $item->name }}</span>
                </a>
            </div>
            @empty
            <div class="col-12">
                <p class="m-0 text-center text-secondary opacity-50 fs-4 py-4">Kategori tidak tersedia.</p>
            </div>
            @endforelse
        </div>
    </div>
</section>

<!-- Produk Terbaru -->
<section>
    <div class="card border-0 shadow-sm">
        <div class="card-body">
            <div class="d-flex align-items-center justify-content-between">
                <div>
                    <h5 class="m-0">Produk Terbaru</h5>
                    <small class="text-secondary">Temukan berbagai macam produk kesukaan kamu</small>
                </div>

                @include('frontend.partials.search')
            </div>

            <div class="row g-4 my-2">
                @forelse ($products as $item)
                <div class="col-6 col-lg-3">
                    @include('frontend.partials.card-product')
                </div>
                @empty
                <div class="col-12">
                    <p class="m-0 text-center text-secondary opacity-50 fs-4 py-4">Produk tidak tersedia</p>
                </div>
                @endforelse
            </div>

            @if (!$products->isEmpty())
            <div class="d-flex justify-content-center mt-5 mb-3">
                <a href="{{ route('produk.index') }}"
                    class="text-decoration-none d-flex align-items-center gap-1 btn btn-outline-primary">
                    <span>Lihat Semua Produk</span> <i class="ri-arrow-right-fill"></i>
                </a>
            </div>
            @endif
        </div>
    </div>
</section>
@endsection